image: node:10.15.0

pipelines:
  pull-requests:
    '**':
        - step:
            caches:
            - node
            name: build and test in Browser
            script: # Modify the commands below to build your repository.
                - npm install
                - apt-get install unzip
                - ./devtools/scripts/run_browserstack_local.bash
                - npm start &
                - browser=bs ./node_modules/.bin/mocha ./test/end2end/TestRunner.js
