image: node:12.13.1

pipelines:
    custom:  
        build and test in Browser:        
            - step:
                caches:
                    - node
                script:
                    - npm install
                    - apt-get install unzip
                    - ./devtools/scripts/run_browserstack_local.bash
                    - npm run browsertestWithServer
