image: node:12.13.1

pipelines:
     custom: # Pipelines that are triggered manually
        End2End-Tests: # The name that is displayed in the list in the Bitbucket Cloud GUI
            - step:
                caches:
                    - node
                script:
                    - rm -rf ./addons/readme.txt
                    - git commit ./addons/readme.txt -m "deleted before add addons in e2e test run"
                    - git clone https://DudekIn@bitbucket.org/geowerkstatt-hamburg/addons.git
                    - cd addons/cosi
                    - npm install
                    - ls -al
                    - cd ../sdpdownload
                    - npm install
                    - cd ..                    
                    - npm install
                    - npm run buildPortal
                    - apt-get update
                    - apt-get install unzip
                    # make script executable and commit the change, else git-ftp does not work
                    - chmod +x ./devtools/scripts/transfer_to_test_geoportal.sh
                    - git commit devtools/scripts/transfer_to_test_geoportal.sh -m "made transfer_to_test_geoportal.sh executable" 
                    - ./devtools/scripts/transfer_to_test_geoportal.sh
                    # run e2e tests
                    - ./devtools/scripts/run_browserstack_local.bash
                    - npm run browsertestOnGeoportalTest