image: node:12.13.1

pipelines:
    pull-requests:
        - step:
            caches:
                - node
            name: build and test in Browser
            script:
                - npm install
                - apt-get install unzip
                - ./devtools/scripts/run_browserstack_local.bash
                - npm run browsertestWithServer
