image: node:12.13.1

pipelines:
     custom: # Pipelines that are triggered manually
        End2End-Tests: # The name that is displayed in the list in the Bitbucket Cloud GUI
            - step:
                caches:
                    - node
                script:
                    - npm install
                    - npm run buildPortal
                    - apt-get update
                    - apt-get install unzip
                    - apt-get -qq install git-ftp
                    - git config git-ftp.user $LGV_TEST_FTP_USERNAME
                    - git config git-ftp.password $LGV_TEST_FTP_PASSWORD
                    - git config git-ftp.syncroot dist
                    - git config git-ftp.url ftp://$LGV_TEST_FTP_HOST
                    # do init once per ftp target-folder to create and transport the .git-ftp.log file containing the SHA1 of the latest commit, after that do always push.
                    # - git ftp init -vv
                    - git ftp push -b $BITBUCKET_BRANCH --all
                    # run e2e tests
                    - ./devtools/scripts/run_browserstack_local.bash
                    - npm run browsertestOnGeoportalTest